# Generated by Django 3.2.25 on 2025-03-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='movie_spoilers',
            field=models.BooleanField(default=False, verbose_name='Does this post contain spoilers?'),
        ),
    ]
