# Generated by Django 5.1.7 on 2025-03-19 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_movie_spoilers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='movie_image',
            new_name='image',
        ),
    ]
