# Generated by Django 5.1.7 on 2025-03-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_k5wqe1', upload_to='images/'),
        ),
    ]
